[2025-09-28 16:12:18.383] [INFO] [thread_pool_test.cpp:27 initTestLogger] === threads_test 测试开始 ===
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:73 testSafeQueueBasic] === 开始测试 SafeQueue 基础功能 ===
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=2
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=3
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:111 testSafeQueueBasic] 测试1（无容量限制队列）：通过
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=4
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:151 testSafeQueueBasic] 测试2（有容量限制队列）：通过
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:176 testSafeQueueBasic] 测试3（队列exit功能）：通过
[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:177 testSafeQueueBasic] === SafeQueue 基础功能测试结束 ===

[2025-09-28 16:12:18.383] [DEBUG] [thread_pool_test.cpp:184 testSafeQueueTimeout] === 开始测试 SafeQueue 超时等待功能 ===
[2025-09-28 16:12:18.883] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:18.883] [DEBUG] [thread_pool_test.cpp:231 testSafeQueueTimeout] 测试（超时等待功能）：通过
[2025-09-28 16:12:18.883] [DEBUG] [thread_pool_test.cpp:232 testSafeQueueTimeout] === SafeQueue 超时等待功能测试结束 ===

[2025-09-28 16:12:18.883] [DEBUG] [thread_pool_test.cpp:239 testSafeQueueMultiThread] === 开始测试 SafeQueue 多生产者多消费者线程安全 ===
[2025-09-28 16:12:18.883] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=1
[2025-09-28 16:12:18.883] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=2
[2025-09-28 16:12:18.884] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=3
[2025-09-28 16:12:18.933] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=4
[2025-09-28 16:12:18.933] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=5
[2025-09-28 16:12:18.934] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=6
[2025-09-28 16:12:18.983] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=7
[2025-09-28 16:12:18.984] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=8
[2025-09-28 16:12:18.984] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=9
[2025-09-28 16:12:19.034] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=10
[2025-09-28 16:12:19.034] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=11
[2025-09-28 16:12:19.034] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=12
[2025-09-28 16:12:19.084] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=13
[2025-09-28 16:12:19.084] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=14
[2025-09-28 16:12:19.084] [DEBUG] [thread_pool_test.cpp:255 operator()] 多线程任务执行：生产者计数=15
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:292 testSafeQueueMultiThread] 生产者任务总数：实际=15，预期=15
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:293 testSafeQueueMultiThread] 消费者任务总数：实际=15，预期=15
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:294 testSafeQueueMultiThread] 测试（多生产者多消费者线程安全）：通过
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:295 testSafeQueueMultiThread] === SafeQueue 多生产者多消费者线程安全测试结束 ===

[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:303 testThreadPoolBasic] === 开始测试 ThreadPool 基础功能 ===
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:312 testThreadPoolBasic] 立即启动线程池：isStarted=1，isExited=0
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=3
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=2
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=5
[2025-09-28 16:12:19.184] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=4
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:350 testThreadPoolBasic] 立即启动线程池退出后：isExited=1
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:355 testThreadPoolBasic] 延迟启动线程池：isStarted=0，isExited=0
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=3
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=4
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=2
[2025-09-28 16:12:19.284] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=5
[2025-09-28 16:12:19.384] [DEBUG] [thread_pool_test.cpp:401 testThreadPoolBasic] 测试（线程池基础功能）：通过
[2025-09-28 16:12:19.384] [DEBUG] [thread_pool_test.cpp:402 testThreadPoolBasic] === ThreadPool 基础功能测试结束 ===

[2025-09-28 16:12:19.384] [DEBUG] [thread_pool_test.cpp:409 testThreadPoolExceptions] === 开始测试 ThreadPool 异常处理 ===
[2025-09-28 16:12:19.385] [DEBUG] [thread_pool_test.cpp:420 testThreadPoolExceptions] 构造函数异常1捕获成功：ThreadPool::ThreadPool(): threadNum must be greater than 0
[2025-09-28 16:12:19.385] [DEBUG] [thread_pool_test.cpp:438 testThreadPoolExceptions] start()异常捕获成功：ThreadPool::start(): thread pool is exited
[2025-09-28 16:12:19.385] [WARN] [../handy/thread_pool.cpp:148 join] ThreadPool::join(): thread pool is not started
[2025-09-28 16:12:19.385] [DEBUG] [thread_pool_test.cpp:455 testThreadPoolExceptions] addTask()异常捕获成功：ThreadPool::addTask(): thread pool is not started
[2025-09-28 16:12:19.385] [DEBUG] [thread_pool_test.cpp:483 testThreadPoolExceptions] 测试（线程池异常处理）：通过
[2025-09-28 16:12:19.385] [DEBUG] [thread_pool_test.cpp:484 testThreadPoolExceptions] === ThreadPool 异常处理测试结束 ===

[2025-09-28 16:12:19.385] [DEBUG] [thread_pool_test.cpp:491 testThreadPoolMultiTask] === 开始测试 ThreadPool 多线程任务执行与容量控制 ===
[2025-09-28 16:12:19.485] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=1，延迟=100ms，当前计数=1
[2025-09-28 16:12:19.485] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=0，延迟=100ms，当前计数=2
[2025-09-28 16:12:19.485] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=2，延迟=100ms，当前计数=3
[2025-09-28 16:12:19.585] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=3，延迟=100ms，当前计数=4
[2025-09-28 16:12:19.585] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=5，延迟=100ms，当前计数=5
[2025-09-28 16:12:19.585] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=4，延迟=100ms，当前计数=6
[2025-09-28 16:12:19.685] [DEBUG] [thread_pool_test.cpp:510 testThreadPoolMultiTask] 任务执行中等待数量：1（应小于等于10）
[2025-09-28 16:12:19.685] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=6，延迟=100ms，当前计数=7
[2025-09-28 16:12:19.685] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=7，延迟=100ms，当前计数=8
[2025-09-28 16:12:19.685] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=8，延迟=100ms，当前计数=9
[2025-09-28 16:12:19.785] [DEBUG] [thread_pool_test.cpp:65 paramTestTask] 带参数任务执行：编号=9，延迟=100ms，当前计数=10
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:525 testThreadPoolMultiTask] 多任务执行总数：实际=10，预期=10
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:541 testThreadPoolMultiTask] 超过容量添加任务：成功=10，容量=10
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=2
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=3
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:547 testThreadPoolMultiTask] 测试（多线程任务执行与容量控制）：通过
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:548 testThreadPoolMultiTask] === ThreadPool 多线程任务执行与容量控制测试结束 ===

[2025-09-28 16:12:19.885] [WARN] [../handy/thread_pool.cpp:112 ~ThreadPool] ThreadPool::~ThreadPool(): 7 tasks are not processed before exit
[2025-09-28 16:12:19.885] [DEBUG] [thread_pool_test.cpp:555 testThreadPoolTaskException] === 开始测试 ThreadPool 任务异常处理 ===
[2025-09-28 16:12:19.886] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:19.886] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=3
[2025-09-28 16:12:19.886] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=2
[2025-09-28 16:12:19.886] [ERROR] [../handy/thread_pool.cpp:221 workerLoop] ThreadPool::workerLoop(): task execution failed; 测试任务主动抛出异常
[2025-09-28 16:12:19.886] [ERROR] [../handy/thread_pool.cpp:221 workerLoop] ThreadPool::workerLoop(): task execution failed; 测试任务主动抛出异常
[2025-09-28 16:12:21.886] [DEBUG] [thread_pool_test.cpp:580 testThreadPoolTaskException] 异常处理测试：正常任务执行数=3，预期=3
[2025-09-28 16:12:21.886] [DEBUG] [thread_pool_test.cpp:53 baseTestTask] 基础任务执行：当前计数=1
[2025-09-28 16:12:22.386] [DEBUG] [thread_pool_test.cpp:595 testThreadPoolTaskException] 测试（任务异常处理）：通过
[2025-09-28 16:12:22.386] [DEBUG] [thread_pool_test.cpp:596 testThreadPoolTaskException] === ThreadPool 任务异常处理测试结束 ===

[2025-09-28 16:12:22.386] [INFO] [thread_pool_test.cpp:34 destroyTestLogger] === threads_test 测试结束 ===
